### DISCUSSION TITLE
WebP TMS

### DISCUSSION THREAD

**Discussion by liamdiprose** [mapproxy/mapproxy#1110] [Q&A] [answered]
Hello,

The documentation states that PNG is the internal format of tiles. How can I serve them as WebP?

Thank you,
Liam

**Comment by liamdiprose** [comment, marked as answer]
I think I've cracked it. I needed to put `format: image/webp` in the cache config and `format: image/png` in the source config:

```yaml
sources:
  mysource:
    req:
      format: image/png
      # .. etc ..

caches:
  mycache:
    format: image/webp
    sources: [mysource]
    # .. etc ..
```

Hope this helps someone and thank you for this very tidy project.
