### ISSUE TITLE
using opacity on cache raises warning but works fine

### ISSUE THREAD

**Issue by weskamm** [mapproxy/mapproxy#1053]
Like the title says, there is a warning raised when using opacity on a cache:

"unknown 'opacity' in caches...."

But it does work well, so the warning does not make sense at all.

Config example:
```
caches:
  mycache:
    sources: [mysource]
    image:
      opacity: 0.7
```

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 3.8 with mod_wsgi 4.5.9):
* Server type and version:
* Operating System and version:
