### ISSUE TITLE
Enable (basic) logging config via main config file instead of logging.ini file

### ISSUE THREAD

**Issue by simonseyock** [mapproxy/mapproxy#1063]
something like:
```yaml
globals:
  logging:
    level: debug
```
