### ISSUE TITLE
`Tiles` parameter in WMS request results in error

### ISSUE THREAD

**Issue by dfstimo** [mapproxy/mapproxy#1096]
I have configured MapProxy with a WMS source. However, whenever the parameter `TILED` is set to true, the request returns the following error:
```
Request too large or invalid BBOX
```

When it's set to false or when it's removed, it works fine. This is an example request:
```
http://localhost/mapproxy/service?REQUEST=GetMap&SERVICE=WMS&VERSION=1.3.0&FORMAT=image%2Fpng&STYLES=&TRANSPARENT=TRUE&LAYERS=air_traffic&TILED=true&WIDTH=256&HEIGHT=256&CRS=EPSG%3A3857&BBOX=962800.8082800806%2C6439361.010856388%2C962953.6823366509%2C6439513.884912958
```

I have tried different grid configurations, all resulting in the same error. Here is my config:
```yaml
sources:
  geoserver:
    type: wms
    concurrent_requests: 4
    req:
      url: http://geoserver:8080/geoserver/dipul/wms?
      layers: "dipul:flugplaetze,dipul:flughaefen"
      transparent: true
      format: image/png

layers:
  - name: all
    title: All Layers
    sources: [all]

caches:
  all:
    sources: [geoserver]
    grids: [germany]

grids:
  germany:
    srs: 'EPSG:3857'
    bbox: [599266.3018,5946189.3044,1707297.4638,7399104.3380]
    tile_size: [256, 256]
    bbox_srs: 'EPSG:3857'
```

The problem is very similar to this problem from the mailing list:
https://lists.osgeo.org/pipermail/mapproxy/2021-March/002991.html
