### ISSUE TITLE
Customizable UID-Setup in docker-compose.yml

### ISSUE THREAD

**Issue by DenisTahsinoglou** [mapproxy/mapproxy#1174]
The docker container runs default with UID 1000. In our environment and perhaps also on others, the first user created gets the UID 1000. Therefore the container runs with the permissions of this user on the host system.

To prevent this currently one has to create a Dockerfile from the beginning, as long as the root permissions are still active.

To have a developer friendly behaviour it would be preferable to configure the UID, GID and USER NAME in the docker-compose.yaml, so the Dockerfile is not needed.

If you have any questions feel free to ask.

Greetings
Denis

**Comment by simonseyock** [comment]
Hello, I opened this PR for this issue: https://github.com/mapproxy/mapproxy/pull/1177

I added build args so you shoould be able to do something like this:

```yaml
services:
  mapproxy:
    build:
      context: https://github.com/mapproxy/mapproxy.git#4.1.2
      args:
        USER_UID: 1200
        USER_GID: 1200
```

Is this sufficient for your needs? I think it would be messy to change the uid in the entrypoint ...

Feel free to comment on the draft PR
