### ISSUE TITLE
Inverted Y axis when displaying MBTiles in QGIS

### ISSUE THREAD

**Issue by mofoyoda** [mapproxy/mapproxy#178]
I've created an MBTiles cache with ```mapproxy-seed``` and added it as a raster layer in QGIS. The layer displays incorrectly - Y coordinates seem to be inverted (see my screenshots below). 
Is there a configuration key to store Y coordinates properly?

My configuration is quite simple: 
```
services:
  demo:
  kml:
  tms:
  wmts:
  wms:
    srs: ['EPSG:4326', 'EPSG:3857', 'EPSG:900913']
    image_formats: ['image/jpeg', 'image/png']

layers:
  - name: mbtiles_basemap
    title: mbtiles_basemap
    sources: [mbtiles_basemap_cache]

caches:
  mbtiles_basemap_cache:
    grids: [gmerc]
    sources: [mbtiles_basemap_src]
    link_single_color_images: true
    minimize_meta_requests: true
    cache:
      type: mbtiles
      filename: basemap.mbtiles

sources:
  mbtiles_basemap_src:
    type: mapnik
    mapfile: basemap.xml

grids:
  gmerc:
    srs: "EPSG:3857"
    origin: nw
    min_res: 156543.03392804097
    tile_size: [256, 256]

globals:
  cache:
   base_dir: 'cache/'
   lock_dir: 'cache/locks'
   meta_size: [9, 9]
   meta_buffer: 0
  image:
      resampling_method: bicubic
      paletted: false
      formats:
        image/png:
          mode: RGB
          colors: 0
```

![screen shot 2015-04-02 at 15 10 41](https://cloud.githubusercontent.com/assets/5087411/6963799/d009dfc2-d94b-11e4-9a3b-af657480add4.png)

![screen shot 2015-04-02 at 15 10 51](https://cloud.githubusercontent.com/assets/5087411/6963828/260f0348-d94c-11e4-9163-d9a9345b43fd.png)
