### ISSUE TITLE
Basic auth header not added to request

### ISSUE THREAD

**Issue by smesdaghi** [mapproxy/mapproxy#182]
adding username:password to the url does not add basic auth header to the request. The destination url is a geoserver instance which uses geonode extension for authentication. In the example below, if I leave out the `headers: Authorization ..` section, i get a LayerNotDefined exception.
```
secure_source:
    type: wms
    wms_opts:
      version: 1.3.0
    http:
      headers:
        Authorization: Basic YWRtaW46Z2Vvc2VydmVy
    req:
      url: http://admin:geoserver@192.168.99.100/geoserver/wms?
      layers: geonode:ne_50m_admin_0_countries
```
I'm using MapProxy==1.8.0. Below is the http request going out as a result of running a seed command:
```
GET /geoserver/wms?styles=&format=image%2Fpng&height=1104&bbox=-20037508.3428,9236039.00175,-9236039.00175,20037508.3428&layers=geonode%3Ane_50m_admin_0_countries&crs=EPSG%3A3857&service=WMS&request=GetMap&width=1104&version=1.3.0 HTTP/1.1
Accept-Encoding: identity
Host: 192.168.99.100
Connection: close
User-Agent: MapProxy-1.8.0
```
Same request with `curl` (with credentials) gets the image. With `wget` I had to add the `--auth-no-challenge` flag (in addition to credentials) as it was not passing the Auth header either. Our geoserver setup allows anonymous requests but uses authorization at layer level. The problem is most likely because of our setup but you've been so thorough with mapproxy that I figured you might choose to add something like a `http.force_auth` option.
