### ISSUE TITLE
possibility to define a default png to be rendered outside the coverage of a source

### ISSUE THREAD

**Issue by jaykayone** [mapproxy/mapproxy#227]
Using
```
  bgSource:
    type: tile
    url: 'file:///mapproxy/multimapproxy_conf/bg.png'
    grid: GLOBAL_WEBMERCATOR_4_V3
```

works in some cases, but not with metatiling
