### ISSUE TITLE
io.UnsupportedOperation in Python3

### ISSUE THREAD

**Issue by kitzilla** [mapproxy/mapproxy#282]
Hello,

I have been migrating my application stack from Python 2.7 to 3.4 including MapProxy.
My Environment is
```
    OS: Amazon Linux AMI release 2016.09 (Almost CentOS 6)
    MapProxy: 1.9.0
    Python: 3.4.3
    Pillow: 3.4.2
    WSGI: Nginx 1.10.1 + uWSGI 2.0.14
    Virtual Environment?: Yes
```
Configurations
mapproxy.yaml
```
services:
  demo:
  tms:
    use_grid_names: true
  kml:
      use_grid_names: true
  wmts:
  wms:
    md:
      title: MapProxy WMS Proxy
      abstract: This is a minimal MapProxy example.

layers:
  - name: osm
    title: OpenStreetMap
    sources: [osm_cache]

caches:
  osm_cache:
    grids  : [ogrid]
    sources: [osm_original]
    disable_storage: true
          
sources:
  osm_original:
    type: tile
    grid: ogrid
    url: http://a.tile.openstreetmap.org/%(z)s/%(x)s/%(y)s.png
     
grids:
  ogrid:
    base: GLOBAL_MERCATOR
    srs: 'EPSG:3857'
    origin: nw
```

uWSGI ini file
```
[uwsgi]
http = 127.0.0.1:10001
virtualenv = /path/to/virtualenv
wsgi-file = /path/to/mapproxy/wsgi.py
processes = 1
threads   = 15
```

Nginx conf (right under http {} )
```
location /mapproxy {
  proxy_pass  http://localhost:10001;
  proxy_set_header Host $http_host;
  proxy_set_header X-Script-Name /mapproxy;
}
```

With the above configurations, I have run uWSGI ( `/path/to/virtualenv/bin/uwsgi --ini /path/to/uwsgi.ini `) and tried to open a tile like http://hostname/mapproxy/tiles/1.0.0/osm/ogrid/9/255/167.png and mapproxy raised the following error which lead to HTTP 502 by Nginx.
```
  File "/path/to/virtualenv/local/lib/python3.4/site-packages/mapproxy/wsgiapp.py", line 204, in __call__
    return resp(environ, start_response)
  File "/path/to/virtualenv/local/lib/python3.4/site-packages/mapproxy/response.py", line 173, in __call__
    start_response(self.status, self.fixed_headers)
  File "/path/to/virtualenv/local/lib/python3.4/site-packages/mapproxy/response.py", line 142, in fixed_headers
    for key, value in iteritems(self.headers):
io.UnsupportedOperation: fileno
```

Contined to the first comment below
