### ISSUE TITLE
use_direct_from_level not working with arcgis sources

### ISSUE THREAD

**Issue by SantiagoHorcajo** [mapproxy/mapproxy#294]
I've been trying to configure use_direct_from_level  for a cache with an arcgis source and it doesn't seem to work.
Thanks in advance

**Comment by olt** [comment]
`use_direct_from_level` is independent from the source, so it is likely an issue with your configuration.

The issue template contains hints on how to report helpful issues. Please use this template, especially the following part:

    ## Steps to Reproduce

**Comment by olt** [comment]
Closing this issue for now. Please reopen if the issue still exists and if you can provide more information.

**Comment by swen100** [comment]
Hi,

I have the same problem. As configured, caching should stop at zoom-level 14. But on my server I can also see the directories 15,16,17,18 and 19.

MapProxy-Version: 1.11.0

Here is my (reduced) config.yaml:
```
services:
  demo:
  wmts:
  tms:
    use_grid_names: true

layers:
  - name: onmaps_test
    title: Test-Karte
    sources: [test_cache]

caches:

  test_cache:
    grids: [GLOBAL_WEBMERCATOR]
    sources: [wms_onmaps]
    meta_size: [4, 4]
    meta_buffer: 0
    request_format: image/png
    link_single_color_images: true
    minimize_meta_requests: true
    use_direct_from_level: 14

sources:
  wms_onmaps:
    type: wms
    concurrent_requests: 4
    wms_opts:
      version: 1.1.1
      featureinfo: false
    supported_srs: ['EPSG:3857', 'EPSG:4326']
    supported_formats: ['image/jpeg', 'image/jpg', 'image/png']
    http:
      ssl_no_cert_checks: true
    req:
      url: https://wms.onmaps.de?
      layers: earth_land,earth_ocean,earth_coastline,earth_admin_borders
      styles: pastell
      transparent: false
      truecolor: true

globals:
  http:
    ssl_no_cert_checks: true
    client_timeout: 300
  
  cache:
    base_dir: '/home2/mapproxy_cache'
    lock_dir: '/tmp'
    meta_size: [4, 4]
    meta_buffer: 0
    link_single_color_images: true
    concurrent_tile_creators: 2

  image:
      resampling_method: bicubic
      paletted: true
      formats:
        image/png:
           encoding_options:
             quantizer: mediancut
           mode: RGB
           colors: 256
           transparent: false
        image/jpg:
           encoding_options:
             quantizer: fastoctree
             jpeg_quality: 90
           mode: P
           colors: 256
           transparent: false
```
