### ISSUE TITLE
Channel merging raises list index out of range 

### ISSUE THREAD

**Issue by DirkThalheim** [mapproxy/mapproxy#296]
We're using the channel merging to combine infrared images with rgb to create cir. So far it worked very well. But lately we stumbled over an error requesting areas that partly have no data. The server shows an internal error and produces the attached [traceback](https://github.com/mapproxy/mapproxy/files/798842/traceback.txt). When requesting the source cache it works with no problems for the same area. 

As example, when we're requesting the WMS with following parameters `SRS=EPSG:31468&BBOX=4403900,5915900,4404650,5916650&WIDTH=6000&HEIGHT=6000` the layers rgb and ir (the source caches) working as expected. cir (the merged cache) throws the error.
 
I think it's a bug and it should be fixed so that the merged cache can display these areas too. 

I investigated the code in merge.py lin 199 and it seems, that src_img_bands does not contain op.src_img. So maybe this should be handled here. I didn't figured out a concrete solution.

We're using MapProxy Version 1.10.0a0-20161027 with Python 2.7.6 and following cache configuration:
```
caches:
  # layer rgb
  cache_dop20_rgb:
    sources: [] 
    grids: [DE_EPSG_25832_DOP]
    format: mixed
    request_format: image/png
    cache:
      type: file
      directory: /local/dop_rgb/DE_EPSG_25832_DOP 
  # layer ir
  cache_dop20_ir:
    sources: [] 
    grids: [DE_EPSG_25832_DOP]
    format: mixed
    request_format: image/png
    cache:
      type: file
      directory: /local/dop_ir/DE_EPSG_25832_DOP 
  # layer cir
  cache_dop20_cir:
     sources:
       r: [{source: cache_dop20_ir, band: 0}]
       g: [{source: cache_dop20_rgb, band: 0}]
       b: [{source: cache_dop20_rgb, band: 1}]
       a: [{source: cache_dop20_ir, band: 3}]
     grids: [DE_EPSG_25832_DOP]
     meta_size: [1, 1]
     meta_buffer: 0
     disable_storage: true
```
