### ISSUE TITLE
Bad polar projections from web mercator source

### ISSUE THREAD

**Issue by malcolmrh** [mapproxy/mapproxy#297]
## Context

Trying to reproject wms or arcgis source from 3857 to a polar Lambert-Azimuthal or stereo projection (eg 3571 or 3413) either get dateline issues (Dalí-esque melting world in 3571), or nearly unrecognizable (3413). For 3571 this happens only from cached layer. Also, I'm not sure why enforcing the supported_srs of the original wms layer creates the same issue as caching.

## Expected Behavior

The example config below shows a working reprojection to 3571 for the layer without caching (`name: usgs`).

## Actual Behavior

3413 example:
![image](https://cloud.githubusercontent.com/assets/7484537/23488021/72d0248e-fe96-11e6-843d-e3772d44a553.png)

3571 example:
![image](https://cloud.githubusercontent.com/assets/7484537/23488042/97552be2-fe96-11e6-8bcf-f12b8032ca9f.png)

## Steps to Reproduce
```
services:
  demo:
  wms:
    srs: ['EPSG:900913', 'EPSG:3857', 'EPSG:3571', 'EPSG:3413']
    image_formats: ['image/jpeg', 'image/png']
    on_source_errors: raise

layers:
  - name: usgs_srs # looks bad in 3571
    title: layer with supported_srs
    sources: [usgs_forcedsrs]
  - name: usgs_cached # looks bad in 3571
    title: cached usgs
    sources: [usgs_cache]
  - name: usgs # looks ok in 3571
    title: test layer from usgs
    sources: [usgs_arcgis]

caches:
  usgs_cache:
    grid: GLOBAL_WEBMERCATOR
    sources: [usgs_arcgis]

sources:
  usgs_arcgis:
    type: arcgis
    req:
      url: http://basemap.nationalmap.gov/arcgis/rest/services/USGSImageryOnly/MapServer
  usgs_forcedsrs:
    type: arcgis
    supported_srs: ['EPSG:3857']
    req:
      url: http://basemap.nationalmap.gov/arcgis/rest/services/USGSImageryOnly/MapServer


grids:


globals:

```

## Your Environment

* Version used: 1.9.0 (Also tried nightly, 1.10.0a0.post20170224)
* Environments: python:3.4 (tried Pillow==3.3.0, 3.4.0, and 4.0.0 with both nightly and 1.9.0)
* Server type and version: nginx:1.10
* Operating System and version: Linux Mint 18.0
