### ISSUE TITLE
Exceptions when accessing tiles with watermark

### ISSUE THREAD

**Issue by olt** [mapproxy/mapproxy#34]
Tile access (TMS/KML/WMTS) is not possible when using the watermark feature. I guess the image_opts get lost when the watermarks are added.

``` yaml

services:
  demo:
  tms:

layers:
    - name: osm
      title: OpenStreetMap
      sources: [osm_cache]

caches:
  osm_cache:
    grids: [global_mercator_osm]
    sources: [osm_tms]
    disable_storage: true
    watermark:
      text: '@ OpenStreetMap contributors'

sources:
  osm_tms:
    type: tile
    grid: global_mercator_osm
    url: http://c.tile.openstreetmap.org/%(tms_path)s.png

grids:
  global_mercator_osm:
    base: GLOBAL_MERCATOR
    num_levels: 18
    origin: nw

```
