### ISSUE TITLE
WMS bbox_srs issue

### ISSUE THREAD

**Issue by DirkThalheim** [mapproxy/mapproxy#357]
Since mapproxy 1.11 there seem to be an issue manually specifying all WMS BBOXes with bbox_srs. Using following config: 
```
services:
  wms:
    srs: ['CRS:84', 'EPSG:4326','EPSG:3857','EPSG:4258',
          'EPSG:25832','EPSG:25833',
          'EPSG:3034','EPSG:3035', 'EPSG:31466', 'EPSG:31467', 'EPSG:31468', 'EPSG:31469',
          'EPSG:5676', 'EPSG:5677', 'EPSG:5678', 'EPSG:5679']
    bbox_srs: 
      - 'CRS:84'
      - 'EPSG:4326'
      - 'EPSG:3857'       
      - srs: 'EPSG:4258'
        bbox: [-35.999991, 18.404252, 53.999994, 79.321963]
      - srs: 'EPSG:4839'
        bbox: [-2275549.54467,-5292558.65892,3682077.51074,4993562.02194]
      - srs: 'EPSG:25832'
        bbox: [247087, 5227094, 947317, 6131781]
        #bbox: [-1475043, 3033051, 2531929, 8225600]
      - srs: 'EPSG:25833'
        bbox: [-1735984, 2876434, 1916709,8025789]
      - srs: 'EPSG:3034'
        bbox: [2122254.2378, 1164627.9290, 5955457.4541, 5021872.0731]
      - srs: 'EPSG:3035'
        bbox: [2426378.0132, 1528101.2618, 6293974.6215, 5446513.5222]
      - srs: 'EPSG:31466'
        bbox: [2411408, 5129732, 3218656, 6235087]
      - srs: 'EPSG:31467'
        bbox: [3175708, 5133776, 4024237,6207551]
      - srs: 'EPSG:31468'
        bbox: [3952421,5152678, 4836381,6189322]
      - srs: 'EPSG:31469'
        bbox: [4718975,5180252, 5646048,6176060]
      - srs: 'EPSG:5676'
        bbox: [2411408, 5129732, 3218656, 6235087]
      - srs: 'EPSG:5677'
        bbox: [3175708, 5133776, 4024237,6207551]
      - srs: 'EPSG:5678'
        bbox: [3952421,5152678, 4836381,6189322]
      - srs: 'EPSG:5679'
        bbox: [4718975,5180252, 5646048,6176060]  
```
With version 1.10 the capabilities showing the specified BBOXes. Since 1.11 however it seems that somehow the srs extend and data extend are mixed. 

We're providing a cache in EPSG:4857 for the whole world, but also want to provide access to WMS in other SRS for Europe or Germany coverage. With the mentioned bug it doesn't work as the described area is to small. Especially in QGIS you are restricted to view this area.

As far as I unterstand the documentation, bbox_srs is to overwrite the BBOXes of all layers.

We experienced this behavior using MapProxy 1.11 and the latest Tarball from GitHub. As mentioned with 1.10.0 it works. Let me know if you need more information.
