### ISSUE TITLE
getCapabilities produces invalid XML with specific yaml data

### ISSUE THREAD

**Issue by anneb** [mapproxy/mapproxy#388]
## Context

If contact information in yaml file contains an ampersand '&', the ampersand is not xml-encoded when copied to the capabilities

## Expected Behavior
User defined strings should be xml-encoded when copied to getcapabilities

## Actual Behavior
User defined strings are not encoded and may produce invalid xml that is not accepted by browsers

## Possible Fix

As a work-around, users can xml encode their strings, 

## Steps to Reproduce
1. create a mapproxy project with metadata to be used in capabilities documents
2. at contact => organisation, add 'Company R&D'
```
services:
  demo:
  tms:
  wmts:
  wms:
    srs: ['EPSG:3857']
    image_formats: ['image/jpeg', 'image/png']
    md:
      # metadata used in capabilities documents
      title: MapProxy WMS Proxy
      abstract: This is the fantastic MapProxy.
      online_resource: http://mapproxy.org/
      contact:
        person: My Name
        position: tech support
        organization: Company R&D
        address: Street 1
        city: My City
        postcode: 12345
        country: my country
        email: email@example.com
      access_constraints:
        This service is intended for educational purposes.
      fees: 'None'

```
layers:
3. request capabilities from mapproxy
4. load result into browser, the browser will complain about invalid xml

## Context

The bug can be easily worked around by xml-encoding in the yaml file, but it may take quite some time to figure out what causes mapproxy to fail

## Your Environment

* Version used: 1.11.0
* Ubuntu 18.04.1 LTS,  Python 2.7.15,  with libapache2-mod_wsgi 4.5.17-1:
* Server type and version:
* Operating System and version:  Ubuntu 18.04.1 LTS
