### ISSUE TITLE
Wrong TMS layer capabilities

### ISSUE THREAD

**Issue by gfiedler** [mapproxy/mapproxy#392]
The zoom level of the TMS service is different from the zoom level of the tile source.

## Context

```
mapproxy-util grids mapproxy.yaml 
mygrid:
    Configuration:
        base: 'GLOBAL_WEBMERCATOR'
        bbox*: [-20037508.342789244, -20037508.342789244, 20037508.342789244, 20037508.342789244]
        num_levels: 3
        origin*: 'ul'
        tile_size*: [256, 256]
    Levels: Resolutions, # x * y = total tiles
        00:  156543.03392804097, #      1 * 1      =          1
        01:  78271.51696402048,  #      2 * 2      =          4
        02:  39135.75848201024,  #      4 * 4      =         16
```

## Expected Behavior

```
<?xml version="1.0"?>
 <TileMap version="1.0.0">
  <Title>AWS Terrain Tiles</Title>
  <Abstract></Abstract>
  <SRS>OSGEO:41001</SRS>
  <BoundingBox minx="-20037508.3428" miny="-20037508.3428" maxx="20037508.3428"
maxy="20037508.3428" />
  <Origin x="-20037508.3428" y="-20037508.3428" />
  <TileFormat width="256" height="256" mime-type="image/png" extension="png" />
  <TileSets profile="global-mercator">
    <TileSet href="http://localhost:8080/tms/1.0.0/mylayer/EPSG3857/0" units-per-pixel="156543.033928" order="0" />
    <TileSet href="http://localhost:8080/tms/1.0.0/mylayer/EPSG3857/1" units-per-pixel="78271.516964" order="1" />
    <TileSet href="http://localhost:8080/tms/1.0.0/mylayer/EPSG3857/2" units-per-pixel="39135.758482" order="2" />
  </TileSets>
</TileMap>
```

## Actual Behavior

TMS GetCapabilities has only 2 tile sets:

```
<?xml version="1.0"?>
 <TileMap version="1.0.0">
  <Title>AWS Terrain Tiles</Title>
  <Abstract></Abstract>
  <SRS>OSGEO:41001</SRS>
  <BoundingBox minx="-20037508.3428" miny="-20037508.3428" maxx="20037508.3428"
maxy="20037508.3428" />
  <Origin x="-20037508.3428" y="-20037508.3428" />
  <TileFormat width="256" height="256" mime-type="image/png" extension="png" />
  <TileSets profile="global-mercator">
    <TileSet href="http://localhost:8080/tms/1.0.0/mylayer/EPSG3857/0" units-per-pixel="78271.516964" order="0" />
    <TileSet href="http://localhost:8080/tms/1.0.0/mylayer/EPSG3857/1" units-per-pixel="39135.758482" order="1" />
  </TileSets>
</TileMap>
```

http://localhost:8080/tms/1.0.0/mylayer/EPSG3857/0/0/0.png

is identical with

https://s3.amazonaws.com/elevation-tiles-prod/terrarium/1/0/0.png

There are more tiles available for zoom level = 0:

http://localhost:8080/tms/1.0.0/mylayer/EPSG3857/0/1/0.png
http://localhost:8080/tms/1.0.0/mylayer/EPSG3857/0/0/1.png
http://localhost:8080/tms/1.0.0/mylayer/EPSG3857/0/1/1.png

## Possible Fix

There seems to be an off-by-one error of the z-coordinate.

## Steps to Reproduce

```
services:
  demo:
  tms:
    use_grid_names: false
    # origin for /tiles service
    origin: 'sw'
  kml:
      use_grid_names: true
  wmts:
  wms:
    md:
      title: MapProxy WMS Proxy
      abstract: This is a minimal MapProxy example.

layers:
  - name: mylayer
    title: AWS Terrain Tiles
    sources: [mycache]

caches:
  mycache:
    sources: [mysource]
    grids: [mygrid]

sources:
  mysource:
    type: tile
    grid: mygrid
    url: https://s3.amazonaws.com/elevation-tiles-prod/terrarium/%(z)s/%(x)s/%(y)s.png

grids:
    mygrid:
        base: GLOBAL_WEBMERCATOR
        num_levels: 3
```

http://localhost:8080/demo/?tms_capabilities&layer=mylayer&srs=EPSG3857

## Your Environment

* Version used: 1.11.0
* Server type and version: Apache/2.4.33 (Unix) mod_wsgi/4.3.0 Python/2.7.9
* Operating System and version:  Debian GNU/Linux 8 (jessie)
