### ISSUE TITLE
`mapserv` auto-discovery does not work

### ISSUE THREAD

**Issue by Turbo87** [mapproxy/mapproxy#404]
## Context

I'm trying to use the following mapserver source:

```
sources:
  mwp_mapserver_bin:
    type: mapserver
    supported_srs: ['EPSG:3857']
    req:
      layers: MWP
      map: foo.map
      transparent: true
    image:
      format: image/png
    mapserver:
      working_dir: ../mapserver
```

according to the documentation and https://github.com/mapproxy/mapproxy/commit/069fb44a10c2f096cc300e438b43f41ae6b6e8b9 the `mapserver.binary` setting is now optional and should automatically find the binary from `PATH`.

Instead of that I'm seeing the following warning:
```
mapproxy.config - WARNING - Missing mapserver binary for source 'mwp_mapserver_bin'
```

## Expected Behavior

`mapproxy` should find the `mapserv` binary automatically

## Actual Behavior

An configuration validator warning is displayed

## Possible Fix

My guess is that https://github.com/mapproxy/mapproxy/blob/1.11.0/mapproxy/config/validator.py#L136-L165 needs to be adjusted to account for the new code introduced in https://github.com/mapproxy/mapproxy/commit/069fb44a10c2f096cc300e438b43f41ae6b6e8b9

## Steps to Reproduce

see above

## Context

see above

## Your Environment

* Version used: 1.11.0
* Environment name and version (e.g. Python 2.7.5 with mod_wsgi 4.5.9): Python 2.7.13
* Operating System and version: Debian Stretch
