### ISSUE TITLE
Disabling /demo due to XSS on 1.11.0

### ISSUE THREAD

**Issue by kyroskoh** [mapproxy/mapproxy#414]
I still receive XSS for 1.11.0 for /demo.

removed 

> demo:

 in line 2
```
services:
  wmts:
    restful: true
    kvp: true
  tms:
    use_grid_names: true
    origin: 'sw'
  wms:
    srs: ['EPSG:4326', 'EPSG:3414']
    image_formats: ['image/png']
```

I would like to disable "Welcome to MapProxy" page. How can I able to block the request?

I tried to use nginx to add in deny all; for location / but it doesn't work.
