### ISSUE TITLE
mapproxy.config - WARNING - unknow 'html' in sources

### ISSUE THREAD

**Issue by tyomik-mnemonic** [mapproxy/mapproxy#431]
`mapproxy.config - WARNING - unknow 'html' in sources` has thrown by terminal
when i run : `mapproxy-seed -c 16 --continue -f mapproxy.yaml -s seed.yaml` , and no one tile has been cashed... o tiles. 

PS  maybe a reason it is that insufficient memory and swp?

settings:
```
services:
  demo:
  tms:
    use_grid_names: true
    origin: 'nw'
  kml:
      use_grid_names: true
  wmts:
    # use restful access to WMTS
    restful: true
    # this is the default template for MapProxy
    restful_template: '/{Layer}/{TileMatrixSet}/{TileMatrix}/{TileCol}/{TileRow}.{Format}'
    # and also allow KVP requests
    kvp: true
  wms:
    md:
      title: MapProxy WMS Proxy
      abstract: This is a minimal MapProxy example.

layers:
  - name: osm_background
    title: osm_background
    sources: [gasps_osm_cache]

caches:
  gasps_osm_cache:
    grids: [osm_grid]
    sources: [gasps_osm_source]
    meta_size: [6, 6]
    meta_buffer: 100

sources:
  gasps_osm_source:
    type: wms
    html:
      client_timeout: 500
    req:
      url: 'http://xxx.local:8080/geoserver/test_osm/wms'
      layers: osm:osm_layerset  
    coverage:
      
      srs: 'EPSG:3857'
grids:
    osm_grid:
        base: GLOBAL_MERCATOR
        srs: 'EPSG:3857'
        origin: nw

globals:
```
and
```
seeds:
  myseed1:
    caches: [gasps_osm_cache]
    # grids: []
    #coverages: [changed_area]
    levels:
      to: 12
    refresh_before:
      time: 2019-9-25T12:35:00
```
