### ISSUE TITLE
MapProxy dosen't display certain uncached tiles

### ISSUE THREAD

**Issue by tyomik-mnemonic** [mapproxy/mapproxy#436]
I face an unnormal behavior of MapProxy on client.

The way of spatial data looks like: |PostgreSQL| --> |GeoServer|wms request| --> |seeding tiles|MapProxy|wmts request| -->|Fronend(OL6)|

My seed.yaml looks like:
```
seeds:
  myseed1:
    caches: [ps_osm_cache]
    levels: [0,1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
    refresh_before:
        time: 2019-12-04T12:35:00
```

dir with cache looks correctly:
![image](https://user-images.githubusercontent.com/42242593/70243827-696b8f00-1784-11ea-88f8-7e88bc610d7a.png)

But some tiles on 13-14 levels work bad

12 zoom level (all is ok):
![image](https://user-images.githubusercontent.com/42242593/70243877-84d69a00-1784-11ea-95ba-f2fd68f06a0d.png)

13 is not (some styles are dead):
![image](https://user-images.githubusercontent.com/42242593/70243902-93bd4c80-1784-11ea-9f07-918b6fe56ea6.png)

14 bad again (but some new correct tiles):

![image](https://user-images.githubusercontent.com/42242593/70243946-a46dc280-1784-11ea-8c7b-da0fd989d092.png)

and from 15 to 19 all is OK!

What is wrong? It isn't mapproxy cache of 13-19, cause I tryied remove all tiles, and did seeding again... result hadn't achived...
And It isn't 'no data' problem, cause wms from geoserver and PostgreSQL info show that all is ok. mapproxy.log hasn't carried any error or warning...I really don't understand what the reason..
