### ISSUE TITLE
Bug in tile locks when using a read-only geopackage

### ISSUE THREAD

**Issue by Guinness1759** [mapproxy/mapproxy#440]
Relevant yaml:
```
layers:
  some_geopackage:
    title: some geopackage
    sources: [ gpkg_cache ]

caches:
  gpkg_cache:
    grids: [ GLOBAL_WEBMERCATOR ]
    sources: [ gpkg_source ]
  gpkg_source:
    grids: [ GLOBAL_GEODETIC ]
    sources: [ ]
    cache:
      type: geopackage
      filename: /my/geopackage/file.gpkg
      table_name: my_table
```
Error thrown:
`FileNotFoundError: [Errno 2] No such file or directory: '/srv/mapproxy/config/./cache_data/tile_locks/(...).lck`

(critical - causes server to crash)

## Possible Fix
in `mapproxy/cache/base.py`, wrap function `lock_filename`'s return clause with `os.path.absname`

## Environment
* https://hub.docker.com/r/pdok/mapproxy
