### ISSUE TITLE
upscale_tiles replaces transparency with black

### ISSUE THREAD

**Issue by zeevogels** [mapproxy/mapproxy#443]
## Context
I tried to use the new upscale_tiles option in a cache to create retina tiles for a source that does not give me any. Unfortunately the upscaled tiles transparency has been replaced with black. 

Not sure if this is the same problem: https://github.com/mapproxy/mapproxy/issues/429 ?

## Expected Behavior
Transparent images should keep transparency when upscaled.

## Actual Behavior
Transparency replaced with black color.

## Steps to Reproduce

1. Configure something like this and set a tileurl  that returns images with transparency in the source. 

```
grids:
  mercator:
    base: GLOBAL_MERCATOR
    origin: nw
  mercator_2x:
    base: mercator
    tile_size: [512,512]

caches: 
  ps_cache:
    grids: [mercator]
    sources: [ps]
  ps_cache_2x:
    upscale_tiles: 1
    grids: [mercator_2x]
    sources: [ps_cache]

sources:
  ps:
    type: tile
    url: https://myxyztileurl.com
    grid: mercator
    transparent: true
    on_error:
      204:
        response: transparent
        cache: True
      404:
        response: transparent
        cache: True
```

2. request any tile through xyz (tms has the same outcome)
http://localhost:8080/tiles/1.0.0/{layername}/EPSG900913/{x}/{y}/{z}.png

## Your Environment

* Version used: 1.12.0
* Environment name and version (e.g. Python 2.7.5 with mod_wsgi 4.5.9): python:3.7
* Running in docker container created with https://github.com/PDOK/mapproxy-docker
