### ISSUE TITLE
WMS source supported_srs not always respected

### ISSUE THREAD

**Issue by b3nn0** [mapproxy/mapproxy#445]
Mapproxy 1.12.0
In some cases, the supported_srs parameter for WMS sources doesn't seem to be respected correctly.

Relevant configuration part:
```yaml
layers:
  - name: overlay_leaftype
    title: overlay_leaftype
    sources: [overlay_leaftype]
caches:
  overlay_leaftype:
    grids: [mercator]
sources:
  overlay_leaftype:
    type: wms
    req:
      url: https://image.discomap.eea.europa.eu/arcgis/services/GioLandPublic/HRL_DominantLeafType_2015/MapServer/WMSServer
      layers: '0'
      transparent: true
    supported_srs: ['EPSG:3857']
grids:
  mercator:
    base: GLOBAL_MERCATOR
    num_levels: 25
    sources: [overlay_leaftype]
```

Usually, when I have a cache in GLOBAL_MERCATOR and my WMS source is e.g. EPSG:25832, everything works fine. The WMS Source is requested in EPSG:25832 and mapproxy reprojects to GLOBAL_MERCATOR and caches.

However, this does not seem to work if the WMS source is EPSG:3857. In this case, MapProxy will NOT request in EPSG:3857, but instead, it will try to request the WMS in EPSG:900913, which the WMS does not support.

My EPSG File defines EPSG:3857 and EPSG:900913 equally:
```
# WGS 84 / Pseudo-Mercator
<900913> +proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m  +nadgrids=@null +wktext  +no_defs <>
# WGS 84 / Pseudo-Mercator
<3857> +proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext  +no_defs <>
```

Sadly, I can't simply change my cache to be in GLOBAL_WEBMERCATOR (EPSG:3857), since I have quite a few users requesting tiles on tiles/1.0.0/overlay_leaftype/EPSG900913.
These users wouldn't be able to reach their tiles any more if I change the cache projection to EPSG3857.

It would be quite nice if mapproxy would allow to configure the cache in one projection and allow querying it in another projection (i.e. on the fly reprojection on cache access, not on source access).
That would allow me to have the cache in EPSG3857 and requests to EPSG900913 would still work.
But that's just a side-note. The original problem is that MapProxy queries the WMS in EPSG900913 instead of the EPSG3857 specified in supported_srs.

EDIT:
Just did some debugging and managed to fix the issue, even though I'm not sure if that's really a good fix - but it works:
```python
diff --git a/mapproxy/source/wms.py b/mapproxy/source/wms.py
index 76a11a0d..507dcf1c 100644
--- a/mapproxy/source/wms.py
+++ b/mapproxy/source/wms.py
@@ -107,8 +107,15 @@ class WMSSource(MapLayer):
         if self.supported_formats and format not in self.supported_formats:
             format = self.supported_formats[0]
         if self.supported_srs:
-            if query.srs not in self.supported_srs:
+            request_srs = None
+            for srs in self.supported_srs:
+                if query.srs == srs:
+                    request_srs = srs
+                    break
+            if request_srs is None:
                 return self._get_transformed(query, format)
+            if query.srs.srs_code != request_srs.srs_code:
+                query.srs = request_srs
         if self.extent and not self.extent.contains(MapExtent(query.bbox, query.srs)):
             return self._get_sub_query(query, format)
         resp = self.client.retrieve(query, format)
```

EDIT2: Another fix would be changing the __eq__ operator for SRS to not only make sure that the definition is equal, but also that the srs-code is equal. However, I'm not sure what implications that would have in other places...
