### ISSUE TITLE
Banding/Upscaling Issue with high resolution raster

### ISSUE THREAD

**Issue by thagorx** [mapproxy/mapproxy#466]
I have a layer that is published by GeoServer (2.12.0) and then cached by MapProxy (1.12.0). The layer is a layergroup on the server consisting of a polygon and a GeoTIFF showing a proximity gradient how the layer looks like delivered by the GeoServer is like this:

![banding on geoserver](https://user-images.githubusercontent.com/28947992/86733852-d18f9580-c031-11ea-98ed-2e494e30db97.PNG)

Nice and smooth gradient but when I open the layer on my mapproxy it looks like this:

![banding on mapproxy](https://user-images.githubusercontent.com/28947992/86733924-e1a77500-c031-11ea-80fe-d784bafa87e4.PNG)

What I think is happening is that MapProxy upscales the image from a higher zoom level. Why this does happen I don't know.

The merge.yaml entry for the layer looks like this:

```
sources:
  layer_name_source:
    type: wms
    http:
      client_timeout: 5 # seconds
    req:
      << : *geoserver_url
      layers:   'layer_name_on_geoserver'
      transparent: true

caches:  
  layer_name_cache:
    cache:
      type: file
      directory: /cache/dir/
      directory_layout: tms
    sources: [layer_name_source]
    grids: [GLOBAL_WEBMERCATOR]

layers:
  - name: layer_name_layer
    title: layer_name
    sources: [layer_name_cache]
```
