### ISSUE TITLE
Cant' put GetLegendGraphic to work

### ISSUE THREAD

**Issue by icemagno** [mapproxy/mapproxy#473]
I'm following this example:
https://github.com/mapproxy/mapproxy/blob/master/mapproxy/config_template/base_config/full_example.yaml

Here's my source:
```
  gebco_wms:
    type: wms
    legendgraphic: true
    req:
      url: https://www.gebco.net/data_and_products/gebco_web_services/web_map_service/mapserv
      layers: GEBCO_LATEST
```

My cache:
```
  gebco_cache:
    grids: [geodetic]
    sources: [gebco_wms]
    link_single_color_images: true
    concurrent_tile_creators: 4
    format: custom_format
    transparent: true
    request_format: image/png
```

And my layer:
```
  - name: gebco
    title: GEBCO Batimetria
    sources: [gebco_cache]
```

When I try to do a `/mapproxy/wms?REQUEST=GetLegendGraphic&VERSION=1.0.0&FORMAT=image/png&WIDTH=20&HEIGHT=20&LAYER=gebco` I receive this error:
`
<WMTException version="1.0.0"> unknown WMS request type 'legendgraphic' </WMTException>
`
What I'm doing wrong?
