### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by projeto-arcanjo** [mapproxy/mapproxy#475]
Can't use Mapproxy in a HTTPS source.

Error is:

`could not retrieve WMS map: Could not verify connection to URL "https://geoaisweb.decea.gov.br/geoserver/ICA/wms?layers=ICA%3ASETOR_FIR&transparent=True&format=image%2Fpng&bbox=-180.0,-90.0,180.0,90.0&width=512&height=256&srs=EPSG%3A4326&request=GetMap&version=1.1.1&service=WMS&styles=": [SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1076)
`
My source is:

```
  SETOR_FIR_wms:
    type: wms
    http:
      ssl_no_cert_checks: true    
    wms_opts:
      legendgraphic: true
      featureinfo: true
    req:
      url: https://geoaisweb.decea.gov.br/geoserver/ICA/wms
      layers: ICA:SETOR_FIR
      transparent: true     
``` 

My cache:

```
  SETOR_FIR_cache:
    grids: [geodetic]
    sources: [SETOR_FIR_wms]
    link_single_color_image: true
    format: custom_format
    request_format: image/png
    transparent: true
```

And my layer

```
  - name: SETOR_FIR
    title: Migração Automática
    sources: [SETOR_FIR_cache]
```
