### ISSUE TITLE
source with clip: true in coverage outputs png inside the coverage with non transparent pixels

### ISSUE THREAD

**Issue by tudorbarascu** [mapproxy/mapproxy#488]
## Context

Having an arcgis source as source for a cache (png) and I have the ``clip: true`` option set then all the tiles inside the coverage generate without transparency.

If I comment the ``clip: true`` part everything works as expected inside the coverage (transparent png's).

```
sources:
  arcgis_server01:
    type: arcgis
    #image:
    #  transparent_color: '#fdfdfd'
    #  transparent_color_tolerance: 0
    opts:
      featureinfo: true
      featureinfo_tolerance: 10
      # featureinfo_return_geometries: true
    supported_srs: ['EPSG:3844']
    coverage:
      # If clip is true, all areas outside the coverage will be converted to transparent pixels.
      # clip: true
      datasource: "PG:service=qtibia_casomes"
      where: "SELECT geom FROM topo.coverage_eterra WHERE id = 1"
      srs: 'EPSG:3844'
    req:
      transparent: true
      layers: show:0,1
      url: https://geoportal.server.ro/geoserve/rest/services/publish_publish/MapServer
    http:
      # defines how long MapProxy should wait for data from source servers
      client_timeout: 40 
      ssl_no_cert_checks: true
```
## Expected Behavior

Whatever tiles are inside the coverage and are transparent in the source should stay transparent if the cache format allows it (png).

## Actual Behavior

All the pngs inside the coverage are without transparency.

## Possible Fix

As  a workaround disable ``clip: true`` permanently or temporary until the seeding of the cache is done.
## Steps to Reproduce

1. 
2.
3.
4.

## Your Environment

* Version used: mapproxy-1.13.0
* Environment name and version (e.g. Python 2.7.5 with mod_wsgi 4.5.9): python 3.8.6 and 3.9.1
* Server type and version:
* Ubuntu 20.01 and Debian Testing (bullseye)
* Operating System and version:
