### ISSUE TITLE
TileGrid.origin_tile doesn't compare origin correct with nw

### ISSUE THREAD

**Issue by olt** [mapproxy/mapproxy#51]
```
grids:
 swiss_grid_new:
   srs: 'EPSG:21781'
   bbox: [420000, 30000, 900000, 360000]
   bbox_srs: 'EPSG:21781'
   res: [250, 100, 50, 20, 10, 5, 2.5, 2, 1.5, 1, 0.5 ,0.25, 0.125, 0.0625]
   origin: 'nw'
```

The WMTS GetCapabilities document that MapProxy generates includes
TileMatrix blocks that look like this:

```
<TileMatrix>
<ows:Identifier>00</ows:Identifier>
<ScaleDenominator>892857.142857</ScaleDenominator>
<TopLeftCorner>420000.0 40000.0</TopLeftCorner>
<TileWidth>256</TileWidth>
<TileHeight>256</TileHeight>
<MatrixWidth>8</MatrixWidth>
<MatrixHeight>6</MatrixHeight>
</TileMatrix>
```
