### ISSUE TITLE
transparent_color doesn't apply when mixing different sorces in a source

### ISSUE THREAD

**Issue by trucheromayor** [mapproxy/mapproxy#556]
¡Congratulations ana Thanks for your great sofwware!

I hope you can attend to the following possible issue.

## Summary

When you define a transparent color in a simple source it works nicely.  But when you define a source composed of different sources it doesn't.

## Context
A mapproxy configuration like the following.
```yaml
layers:
  - name: OI_Copernicus_core003
    title: Copernicus Core003 Seamline
    sources: [core_cache]

  - name: Layer_mixture
    title: Layer_mixture
    sources: [core_cache,OI_cache_AT_2020]

  - name: Cache_mixture
    title: Cache_mixture
    sources: [Cache_mixture]

caches:
  Cache_mixture:
    grids:
    - EPSG3857
    image:
      resampling_method: nearest
    sources: [core_cache,OI_cache_AT_2020]
  core_cache:
    grids:
    - EPSG3857
    sources: [core003_wms]
  OI_cache_AT_2020:
    grids:
    - EPSG3857
    image:
      resampling_method: nearest
    sources: [OI_AT_2020_wms]

sources:
  core003_wms:
    type: wms
    min_scale: 50000
    max_scale: 1000000000
    wms_opts:
         version: 1.3.0
    image:
      transparent_color: '#ffffff'
      transparent_color_tolerance: 20
    req:
      url: https://jeodpp.jrc.ec.europa.eu/jeodpp/services/ows/wms/copernicus/core003?
      layers: OI.Mosaic.NaturalColor.Seamline
      transparent: true

  OI_AT_2020_wms:
    type: wms
    max_scale: 50000
    min_scale: 500
    concurrent_requests: 6
    wms_opts:
         version: 1.3.0
    image:
      transparent_color: '#ffffff'
      transparent_color_tolerance: 20
    req:
      url: https://wsa.bev.gv.at/GeoServer/Interceptor/Wms/OI/INSPIRE_KUNDEN-ea22c974-a9cc-4ef4-93b6-911aca065d6c?SERVICE=WMS&TIME=2020-01-01/2020-12-31
      layers: AT_BEV_OI
      transparent: true
    on_error:
      other:
        response: transparent
        cache: False
```
## Expected Behavior
The mixed cache doesn't apply transparent color

## Actual Behavior
This is the resulting demo
![image](https://user-images.githubusercontent.com/5648254/146331530-25c4c52b-9e79-4f61-8a4b-f3f2180a5563.png)

This is the Layer mixture (a layer mixing simple caches) : It works
![image](https://user-images.githubusercontent.com/5648254/146331704-bbb81a4c-e91b-4522-b102-8a380394f6f2.png)
This is a Layer that points to a cache that is a mixture of caches: It doesn't work
![image](https://user-images.githubusercontent.com/5648254/146331875-40bc5ae4-50ae-4080-960f-63274537a2d4.png)

## Your Environment
* Version used: 1.13.2
* Environment name and version (e.g. Python 2.7.5 with mod_wsgi 4.5.9): 2.7.17
* Server type and version: Azure VM
* Operating System and version:Ubuntu 20.04

Thank you in advance for your assistance.

Jon Garrido
