### ISSUE TITLE
[bug] inconsistent handling of `base_dir`

### ISSUE THREAD

**Issue by tobwen** [mapproxy/mapproxy#565]
## Context
I'm trying to access various cache formats relative to `base_dir`

## Expected Behavior
`directory` and `filename` should work absolute (`/a/b/c/`) and relative (`./a/b/c/` or `a/b/c/`)

## Actual Behavior
`directory` needs to be an absolute path, `filename` can be relative

## Possible Fix
n/a

## Steps to Reproduce
The YAML lives in the current directory, `cache_data`, `locks` and `tile_locks` are subdirectories.
``` yaml
globals:
  cache:
    base_dir: ./cache_data/
    lock_dir: ./locks/
    tile_lock_dir: ./tile_locks/

caches:
  heating-compact:
    sources: []
    grids: [webmercator]
    cache:
      type: compact
      version: 2
      directory: ./cache_data/real-estate-grids/2020/heating/
      # doesn't work: real-estate-grids/2020/heating/
      # doesn't work; ./real-estate-grids/2020/heating/

  heating-mbtiles:
    sources: []
    grids: [webmercator]
    cache:
      type: mbtiles
      filename: real-estate-grids/2020/heating.mbtiles
      # doesn't work: ./real-estate-grids/2020/heating.mbtiles
      # doesn't work: ./cache_data/real-estate-grids/2020/heating.mbtiles
```

## Your Environment
* Version used: 1.14.0.post20220124
* Environment name and version (e.g. Python 2.7.5 with mod_wsgi 4.5.9): Python 3.9.2
* Operating System and version: Debian Bullseye
