### ISSUE TITLE
Export uses wrong tiles when caches convert between image formats

### ISSUE THREAD

**Issue by kannes** [mapproxy/mapproxy#583]
I have some caches:
- The main cache, using `image/png` (as per default), referencing a WMS source
- Based on the main cache as source:
  - One with `image: mixed` and `request_format: png`
  - One with `image/jpeg`
- Based on the mixed cache as source:
  - Another cache with `image/jpeg`

They all use the same grid, the only difference is the format.
All caches are empty as I start this.

If I request some imagery from them via WMTS, they get filled with data.
Everything as expected: PNG tiles for the PNG one, both PNG and JPEG tiles for the mixed one and JPEG tiles for the JPEG one. I also confirmed this by storing the tiles in SQLite caches and inspecting the tile BLOBs.

But when I use `mapproxy-util export` to write any of the non-main caches to a SQLite file, the result is all PNG tiles regardless of the format specified for the cache.

## Context
My goal was to use mapproxy-util export to transform an existing cache into another image format.

## Expected Behavior
The exported tiles should be in the format specified for the cache.

## Actual Behavior
The exported tiles are not in the format specified for the cache.

## Steps to Reproduce
I made an reproducible example based on the public demo available at https://www.orka-mv.de/geodienste/orkamv/demo/
1. Grab the files from https://gist.github.com/kannes/61fe21c861079f717d9776752b696358
2. Launch `mapproxy-util serve-develop wrong-formats-on-export.yml`
3. Launch `bash seed-caches.sh` to do some requests and get tiles from the remote source
4. `mapproxy-util export -f wrong-formats-on-export.yml --source=myjpegcache --grid=mygrid --levels=10 --type=sqlite --dest=export_jpeg`
5. `mapproxy-util export -f wrong-formats-on-export.yml --source=mypngcache --grid=mygrid --levels=10 --type=sqlite --dest=export_png`
6. `mapproxy-util export -f wrong-formats-on-export.yml --source=mymixedcache --grid=mygrid --levels=10 --type=sqlite --dest=export_mixed`
7. Inspect the tiles, e.g. using [sqlitebrowser](https://sqlitebrowser.org/), they are all PNG

## Context
Probably related to #94 and #52

## Your Environment
- MapProxy 1.14.0
- Python 3.8.10
- Ubuntu 20.04

**Comment by kannes** [comment]
Addendum:

It seems to work fine if a base cache is JPEG and one wants to convert to PNG. But maybe everything gets turned into PNG so this might be a red herring. :)

I used this horror in the Gist linked above to test:

```
  myjpegbasecache:
    grids: [mygrid]
    sources: [mysource]
    format: image/jpeg
    image: 
      resampling_method: nearest
      encoding_options:
        jpeg_quality: 5
    disable_storage: false
    cache:
      type: sqlite
      directory: /tmp/myjpegbasecache/
  mypngfromjpegcache:
    grids: [mygrid]
    sources: [myjpegbasecache]
    format: image/png
    disable_storage: false
    cache:
      type: sqlite
      directory: /tmp/mypngfromjpegcache/
```

Then seeded via:
```
curl http://127.0.0.1:8080/wmts/mypngfromjpegcachelayer/mygrid/10/23/11.jpeg > /dev/null
curl http://127.0.0.1:8080/wmts/mypngfromjpegcachelayer/mygrid/10/24/11.jpeg > /dev/null
curl http://127.0.0.1:8080/wmts/mypngfromjpegcachelayer/mygrid/10/24/12.jpeg > /dev/null
```

and exported:

`mapproxy-util export -f debugging.yml --source=mypngfromjpegcache --grid=mygrid --levels=10 --type=sqlite --dest=mypngfromjpegcache`

The resulting SQLite export contained all PNG tiles.
