### ISSUE TITLE
bulk_meta_tiles dimensions error

### ISSUE THREAD

**Issue by traviskirstine** [mapproxy/mapproxy#597]
It appears using bulk_meta_tiles is no longer working as expected with version 1.15.1.  When attempting to use a WMTS tile source I will now get this error:

TypeError: store_tiles() missing 1 required positional argument: 'dimensions'

```yaml
## configuration ##
services:
   demo:
   wmts:
   wms:
      srs: ['EPSG:3857','EPSG:900913','EPSG:4326','EPSG:4269']
      image_formats: ['image/jpeg','image/png','png8']

globals:
   http:
      ssl_no_cert_checks: true
   cache:
      base_dir: ./caches
      lock_dir: ./locks
      bulk_meta_tiles: true
      meta_size: [8,8]
      # meta_buffer: 20
   image:
      paletted: false
      formats:
         png8:
            format: image/png8
            mode: P
            colors: 256
            transparent: true
         png:
            format: image/png
            mode: RGBA
            transparent: true
         jpg:
            encoding_options:
               jpeg_quality: 80
grids:
   merc_grid_v2:
      origin: 'nw'
      bbox: [-20037700, -30241100, 20037700, 30241100] # from TopLeftCorner of TileMatrixSet in GetCapabilitis
      srs: EPSG:3857
      res: [ # mapproxy-util scales --as-res-conf using value from ScaleDenominator in GetCapabilities
           #  res            level     scale @90.7 DPI
         156543.0339033477, #  0   559082263.94052744
          78271.5169516738, #  1   279541131.97026372
          39135.7584758369, #  2   139770565.98513186
          19567.8792379185, #  3    69885282.99256593
           9783.9396189592, #  4    34942641.49628296
           4891.9698094796, #  5    17471320.74814148
           2445.9849047398, #  6     8735660.37407074
           1222.9924523699, #  7     4367830.18703537
            611.4962261850, #  8     2183915.09351769
            305.7481130925, #  9     1091957.54675884
            152.8740565462, # 10      545978.77337942
             76.4370282731, # 11      272989.38668971
             38.2185141366, # 12      136494.69334486
             19.1092570683, # 13       68247.34667243
              9.5546285341, # 14       34123.67333621
              4.7773142671, # 15       17061.83666811
              2.3886571335, # 16        8530.91833405
              1.1943285668, # 17        4265.45916703
              0.5971642834, # 18        2132.72958351
              0.2985821417, # 19        1066.36479176
      ]

caches:
   algonquin_2015_cache:
      grids: [merc_grid_v2]
      sources: [algonquin_2015_wmts]
      concurrent_tile_creators: 4
      cache:
         type: sqlite
         directory: ./algonquin_2015_cache

sources:
   algonquin_2015_wmts:
      type: tile
      url: 'https://tiles.arcgis.com/tiles/TJH5KDher0W13Kgo/arcgis/rest/services/ALGONQUIN_2015_TPK/MapServer/WMTS/tile/1.0.0/ALGONQUIN_2015_TPK/default/default028mm/%(z)s/%(y)s/%(x)s'
      grid: merc_grid_v2
      transparent: true
      on_error:
         404:
            response: transparent
            cache: false
      coverage:
          bbox: [-79.1660398611901, 45.59666084778547, -77.55215737963202, 46.15887350495754]
          srs: 'EPSG:4326'

layers:
   - name: algonquin_2015
     title: ALGONQUIN 2015
     sources: [algonquin_2015_cache]
```
