### ISSUE TITLE
File not found 'liblibproj.a' when calling make_wsgi_app from config.py

### ISSUE THREAD

**Issue by spyke555** [mapproxy/mapproxy#600]
My mapproxy sems to be working OK, however I am seeing the following error message in my apache2 error log:

```
[Sun Sep 11 14:30:20.258763 2022]  mod_wsgi (pid=110123): Failed to exec Python script file '/usr/lib/cgi-bin/config.py'.
[Sun Sep 11 14:30:20.258854 2022]  mod_wsgi (pid=110123): Exception occurred processing WSGI script '/usr/lib/cgi-bin/config.py'.
[Sun Sep 11 14:30:20.259328 2022]  Traceback (most recent call last):
[Sun Sep 11 14:30:20.259433 2022]    File "/usr/lib/cgi-bin/config.py", line 10, in <module>
[Sun Sep 11 14:30:20.259439 2022]      application = make_wsgi_app(r'/home/mapproxy/mapproxy.yaml')
[Sun Sep 11 14:30:20.259446 2022]    File "/usr/local/lib/python3.10/dist-packages/mapproxy/wsgiapp.py", line 57, in make_wsgi_app
[Sun Sep 11 14:30:20.259472 2022]      conf = load_configuration(mapproxy_conf=services_conf, ignore_warnings=ignore_config_warnings)
[Sun Sep 11 14:30:20.259482 2022]    File "/usr/local/lib/python3.10/dist-packages/mapproxy/config/loader.py", line 2183, in load_configuration
[Sun Sep 11 14:30:20.259488 2022]      return ProxyConfiguration(conf_dict, conf_base_dir=conf_base_dir, seed=seed,
[Sun Sep 11 14:30:20.259497 2022]    File "/usr/local/lib/python3.10/dist-packages/mapproxy/config/loader.py", line 53, in __init__
[Sun Sep 11 14:30:20.259502 2022]      self.load_globals(conf_base_dir=conf_base_dir)
[Sun Sep 11 14:30:20.259511 2022]    File "/usr/local/lib/python3.10/dist-packages/mapproxy/config/loader.py", line 62, in load_globals
[Sun Sep 11 14:30:20.259516 2022]      self.globals = GlobalConfiguration(conf_base_dir=conf_base_dir,
[Sun Sep 11 14:30:20.259523 2022]    File "/usr/local/lib/python3.10/dist-packages/mapproxy/config/loader.py", line 347, in __init__
[Sun Sep 11 14:30:20.259529 2022]      self.preferred_srs = preferred_srs(self.conf.get('srs', {}))
[Sun Sep 11 14:30:20.259535 2022]    File "/usr/local/lib/python3.10/dist-packages/mapproxy/config/loader.py", line 323, in preferred_srs
[Sun Sep 11 14:30:20.259540 2022]      from mapproxy.srs import SRS, PreferredSrcSRS
[Sun Sep 11 14:30:20.259547 2022]    File "/usr/local/lib/python3.10/dist-packages/mapproxy/srs.py", line 26, in <module>
[Sun Sep 11 14:30:20.259551 2022]      from mapproxy.proj import USE_PROJ4_API
[Sun Sep 11 14:30:20.259559 2022]    File "/usr/local/lib/python3.10/dist-packages/mapproxy/proj.py", line 282, in <module>
[Sun Sep 11 14:30:20.259564 2022]      res = try_import()
[Sun Sep 11 14:30:20.259571 2022]    File "/usr/local/lib/python3.10/dist-packages/mapproxy/proj.py", line 155, in try_libproj_import
[Sun Sep 11 14:30:20.259576 2022]      libproj = init_libproj()
[Sun Sep 11 14:30:20.259582 2022]    File "/usr/local/lib/python3.10/dist-packages/mapproxy/proj.py", line 58, in init_libproj
[Sun Sep 11 14:30:20.259587 2022]      libproj = load_library('libproj')
[Sun Sep 11 14:30:20.259593 2022]    File "/usr/local/lib/python3.10/dist-packages/mapproxy/util/lib.py", line 65, in load_library
[Sun Sep 11 14:30:20.259596 2022]      lib = load_library_(lib_name, locations_conf)
[Sun Sep 11 14:30:20.259602 2022]    File "/usr/local/lib/python3.10/dist-packages/mapproxy/util/lib.py", line 69, in load_library_
[Sun Sep 11 14:30:20.259612 2022]      lib_path = find_library(lib_name)
[Sun Sep 11 14:30:20.259618 2022]    File "/usr/local/lib/python3.10/dist-packages/mapproxy/util/lib.py", line 93, in find_library
[Sun Sep 11 14:30:20.259621 2022]      lib = _find_library(lib_name)
[Sun Sep 11 14:30:20.259626 2022]    File "/usr/lib/python3.10/ctypes/util.py", line 341, in find_library
[Sun Sep 11 14:30:20.259630 2022]      _get_soname(_findLib_gcc(name)) or _get_soname(_findLib_ld(name))
[Sun Sep 11 14:30:20.259635 2022]    File "/usr/lib/python3.10/ctypes/util.py", line 147, in _findLib_gcc
[Sun Sep 11 14:30:20.259639 2022]      if not _is_elf(file):
[Sun Sep 11 14:30:20.259644 2022]    File "/usr/lib/python3.10/ctypes/util.py", line 99, in _is_elf
[Sun Sep 11 14:30:20.259647 2022]      with open(filename, 'br') as thefile:
[Sun Sep 11 14:30:20.259670 2022]  FileNotFoundError: [Errno 2] No such file or directory: b'liblibproj.a'

```

Looks like there is an extra 'lib' appended to libproj.a

I've confirmed that the library is currently installed on my system here:

```
/usr/lib/x86_64-linux-gnu/libproj.a
```

Environment is:
Ubuntu 22.04.1 LTS
Apache 2.4.52 
Python 3.10.4
mod-wsgi 4.9.3
mapproxy 1.15.1

All dependencies from requirements-tests.txt  from this github are installed

My config.py:
```
# WSGI module for use with Apache mod_wsgi or gunicorn

## uncomment the following lines for logging
## create a log.ini with `mapproxy-util create -t log-ini`
#from logging.config import fileConfig
#import os.path
#fileConfig(r'/home/mapproxy/log.ini', {'here': os.path.dirname(__file__)})

from mapproxy.wsgiapp import make_wsgi_app
application = make_wsgi_app(r'/home/mapproxy/mapproxy.yaml')
```

My mapproxy.yaml:
```
services:
  wmts:
  wms:
    md:
      title: Reseau 4X4 FC4X4Q
      abstract: Reseau 4X4 Federe de la Federation des Clubs 4X4 du Quebec
      online_resource: http://www.fc4x4q.com
      contact:
        person: Directeur Reseau
        organization: Federation des Clubs 4X4 du Quebec
        email: reseau@fc4x4q.com
      access_constraints:
        Reserve aux detenteurs d'une carte acces valide de la FC4X4Q. Toute autre acces n'est pas permis.

layers:
  - name: FC4X4Q_Reseau_4X4
    title: FC4X4Q Reseau 4X4
    sources: [fc4x4q_cache]

caches:
  fc4x4q_cache:
    grids: [webmercator]
    sources: [fc4x4q_wms]
    meta_size: [8,8]
    meta_buffer: 250
    cache:
       type: file
       directory: /var/mapproxy/fc4x4q_cache

sources:
  fc4x4q_wms:
    type: wms
    req:
      url: http://<REDACTED>/cgi-bin/qgis_mapserv.fcgi
      layers: FC4X4Q_Reseau_4X4
      # dpi: 90
    http:
      client_timeout: 240
    coverage:
      bbox: [-86.00 , 43.75, -51.00, 63.25]
      srs: 'EPSG:4326'

grids:
    webmercator:
      srs: "EPSG:3857"
      origin: nw
      min_res: 156543.03392804097
```

Any help or insight would be much appreciated. Let me know if you need any further information.
