### ISSUE TITLE
failing GFI requests with special characters (umlauts) when lxml is installed

### ISSUE THREAD

**Issue by tristndev** [mapproxy/mapproxy#602]
We have started to use XLST scripts to transform GetFeatureInfo responses of a source WMS. Generally, this works fine and as expected. However, some of the XML responses contain attributes with special characters (in our case: German umlauts) which lead to misformed XML responses. This behavior also shows when the lxml package is installed but no actual XSLT scripts are enabled.

It seems that the proxying of GFI responses differs depending on the availability of the lxml package.

## Context

The source WMS GetFeatureInfo XML is:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<FeatureInfoResponse xmlns:esri_wms="http://www.esri.com/wms" xmlns="http://www.esri.com/wms">
    <FIELDS OBJECTID="21" AttributeWithÄ="ö" />
</FeatureInfoResponse>
```

✅ MapProxy's proxied XML *without* lxml installed is:
```xml
<?xml version="1.0" encoding="UTF-8"?>

<FeatureInfoResponse xmlns:esri_wms="http://www.esri.com/wms" xmlns="http://www.esri.com/wms">
    <FIELDS OBJECTID="21" AttributeWithÄ="ö" />
</FeatureInfoResponse>
```

❌ MapProxy's proxied XML *with* lxml installed is:
```xml
<FeatureInfoResponse xmlns:esri_wms="http://www.esri.com/wms" xmlns="http://www.esri.com/wms">
    <FIELDS OBJECTID="21" AttributeWith&#228;="&#246;" />
</FeatureInfoResponse>
```

> Note the broken attribute at `&#228;` - also, the XML version tag is omitted.

## Expected Behavior

I would expect both proxied GetFeatureInfo responses to be identical when no XSLT transformations are configured.

## Actual Behavior

When the lxml package is installed, special characters are being transformed into their unicode codes which results in malformed XML documents (when the special characters occur, e.g. as attribute name as in the example above)

## Your Environment

I use the stable [`kartoza/docker-mapproxy`](https://github.com/kartoza/docker-mapproxy) base image with MapProxy 1.14.0. 
lxml is installed in the Dockerfile via `pip install lxml`.

**Comment by weskamm** [comment]
could you provide a url / layer to test?

**Comment by tristndev** [comment]
Unfortunately, our WMS services are not public. I was able to reproduce the issue with a public WMS, the [NRW Unfallatlas](https://unfallatlas.statistikportal.de/_opendata2022.html):
The GFI responses of the layer `Unfallorte` have an attribute `Fußgänger` with different special characters (`ß`and `ä`, in this case). 

Here's the `mapproxy.yaml` configuration for that layer:

```yaml
caches: {}
layers:
- layers:
  - name: Unfallorte
    sources: [Unfallorte_wms]
    title: Unfallorte
  srs: ['EPSG:4326', 'EPSG:25832']
  title: Layers
services:
  demo:
  wms:
    md:
      title: Unfallatlas
    on_source_errors: raise
sources:
  Unfallorte_wms:
    coverage:
      bbox: [5.567798, 47.187915, 15.55503, 55.038438]
      srs: EPSG:4326
    req:
      layers: Unfallorte
      transparent: true
      url: https://www.wms.nrw.de/wms/unfallatlas?
    supported_srs: ['EPSG:4326']
    type: wms
    wms_opts:
      featureinfo: true
      legendurl: https://www.wms.nrw.de/wms/unfallatlas?request=GetLegendGraphic%26version=1.3.0%26format=image/png%26layer=Unfallorte
      version: 1.3.0
```

This GFI request (format `text/xml`) on the source WMS works:
https://www.wms.nrw.de/wms/unfallatlas?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetFeatureInfo&BBOX=53.73525498559196478,10.35376169783363487,53.74283750983437358,10.35999436611201041&CRS=EPSG:4326&WIDTH=748&HEIGHT=910&LAYERS=Unfallorte&STYLES=&FORMAT=image/png&QUERY_LAYERS=Unfallorte&INFO_FORMAT=text/xml&I=306&J=493

While the same request on a local mapproxy instance (here on `localhost:8081`) fails returning a malformed xml: 
http://localhost:8081/service?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetFeatureInfo&BBOX=53.73525498559196478,10.35376169783363487,53.74283750983437358,10.35999436611201041&CRS=EPSG:4326&WIDTH=748&HEIGHT=910&LAYERS=Unfallorte&STYLES=&FORMAT=image/png&QUERY_LAYERS=Unfallorte&INFO_FORMAT=text/xml&I=306&J=493

This is the returned malformed xml:
```xml
<FeatureInfoResponse xmlns="http://www.esri.com/wms" xmlns:esri_wms="http://www.esri.com/wms">
	<FIELDS OBJECTID="508698" Shape="Point" UJAHR="2018" Rad="0" PKW="1" Fu&#223;g&#228;nger="0" Kraftrad="0" Sonstige="0" GKFZ="1" Unfallkategorie="Unfall mit Leichtverletzten"/>
</FeatureInfoResponse>
```

**Note**: The `lxml` package has to be installed for this issue to occur.
