### ISSUE TITLE
Using 'endpoint_url' param makes mapproxy s3.py fail when using 'cloudfront'

### ISSUE THREAD

**Issue by JoseSanchezMoralesIDOX** [mapproxy/mapproxy#673]
I'm using mapproxy 1.12.0, and s3 buckets for caching. Mapproxy is running in Docker and the AWS credentials are passed as variables to docker, i.e.:
-e AWS_ACCESS_KEY_ID=
-e AWS_SECRET_ACCESS_KEY=
-e AWS_DEFAULT_REGION=

The above system works okay, however, after having implemented a `CloudFront` distribution in AWS around the s3 bucket, even though I have explicitly set up the `endpoint_url` value under `globals.cache.s3` in the mapproxy.yaml file, and replacing 
`client = session.client('s3', region_name=self.region_name, endpoint_url=self.endpoint_url)`
by
`client = session.client('cloudfront', region_name=self.region_name, endpoint_url=self.endpoint_url)`
in the s3.py file within the cache folder in mapproxy, I got the following error:

`AttributeError: 'CloudFront' object has no attribute 'head_bucket'`

This is my configuration in the mapproxy.yaml:

```
 os_productxx_27700:
    grids: [uk_bng_abc]
    sources: ['os_xx:os_productxx']
    meta_size: [4, 4]
    meta_buffer: 0
    cache:
      type: s3
      directory: /cache/os_productxx/27700/
      bucket_name: mapproxy-s3-testing

globals:
  cache:
    s3:
      profile_name: default
      region_name: eu-west-1
      endpoint_url: https://xxxxxxxxxxxxx.cloudfront.net
```
 
what am I missing? or is there any further configuration?

Thanks,
Jose.
