### ISSUE TITLE
Downscaling mechanism does not work

### ISSUE THREAD

**Issue by alfmarcua** [mapproxy/mapproxy#687]
## Context

The downscale tiles mechanism does not work despite using the downscale_tiles parameter in the cache.

## Expected Behavior

Tiles should be generated in the missing layers from a higher zoom.

## Actual Behavior

Transparent tiles still appear in downscale zoom levels.

## Possible Fix

The solution found was to modify the file:
/usr/local/lib/python3.10/dist-packages/mapproxy/cache/tile.py In the "_load_tile_coords" function. 

- Condition ( if not created_tiles and self.rescale_tiles ) has been changed to ( if blank_created_tiles and self.rescale_tiles ).
- Added the next code right before the previous condition:
         blank_created_tiles = False
            for tile in created_tiles:
                  if tile.source_image().mode == 'RGBA':
                      if all(tile.source_image().load()[x, y][3] == 0 for x in range(tile.source_image().width) for y in range(tile.source_image().height)) :
                          blank_created_tiles = True

## Steps to Reproduce

1. Create a cache with missing zooms.
2. Add the parameter downscale_tiles with any value greater or equal to 1.
3. Check if there is any tile of missing zooms generated from larger zooms.

## Context

The aim was to ensure that there were no missing zooms in those layers that required it.

## Your Environment

* Version used: checked in MapProxy 1.14 and MapProxy 1.16
* Environment name and version: Python 3.10
* Server type and version:
* Operating System and version: Ubuntu

**Comment by weskamm** [comment]
closing due to inactivity, feel free to reopen

**Comment by alfmarcua** [comment]
And an example configuration is provided with the following yaml

```yaml
services:
  demo:
  tms:
    use_grid_names: true
    origin: 'nw'
  kml:
      use_grid_names: true
  wmts:
  wms:
globals:
  cache:
    meta_size: [4, 4]
    bulk_meta_tiles: false
    minimize_meta_requests: true
    concurrent_tile_creators: 16
    meta_buffer: 96
    link_single_color_images: true
grids:
  EPSG3857:
    base: GLOBAL_WEBMERCATOR
    num_levels: 21
layers:
- name: OI_IT_2012
  sources:
  - OI_cache_IT_2012
  title: OI_IT_2012
caches:
  OI_cache_IT_2012:
    cache:
      type: sqlite
    grids:
    - EPSG3857
    image:
      resampling_method: nearest
    sources:
    - OI_cache_IT_2012_z10_z11
    - OI_cache_IT_2012_z12_z18
  OI_cache_IT_2012_z10_z11:
    cache:
      type: sqlite
    downscale_tiles: 1
    grids:
    - EPSG3857
    image:
      resampling_method: nearest
    meta_size:
    - 1
    - 1
    sources:
    - OI_IT_2012_wms_z10_z12
  OI_cache_IT_2012_z12_z18:
    cache:
      type: sqlite
    grids:
    - EPSG3857
    image:
      resampling_method: nearest
    sources:
    - OI_IT_2012_wms_z12_z18
sources:
  OI_IT_2012_wms_z10_z12:
    concurrent_requests: 6
    coverage: &id001
      clip: true
      datasource: static/IT.txt
      srs: EPSG:3857
    http: &id002
      client_timeout: 300
    max_scale: 1000000
    min_scale: 250000
    on_error:
      other:
        cache: false
        response: transparent
    req: &id003
      layers: OI.ORTOIMMAGINI.2012.32
      transparent: true
      url: http://wms.pcn.minambiente.it/ogc?map=/ms_ogc/WMS_v1.3/raster/ortofoto_colore_12.map
    type: wms
    wms_opts: &id004
      version: 1.3.0
  OI_IT_2012_wms_z12_z18:
    concurrent_requests: 6
    coverage: *id001
    http: *id002
    max_scale: 250000
    min_scale: 500
    on_error:
      other:
        cache: false
        response: transparent
    req: *id003
    type: wms
    wms_opts: *id004
```
