### ISSUE TITLE
Redis - handle errors in order to fallback to source layer

### ISSUE THREAD

**Issue by CL-SHLOMIKONCHA** [mapproxy/mapproxy#692]
Redis has no error handler so when server is down or raise an error, MapProxy is not able to serve the specific Redis cached layer.
 
## Context

The below example shows an `osm cache` layer cached by redis (`osm_redis_cache`), when Redis server is down or unavailable, MapProxy throws a 'ConnectionError' from Redis server and is not able to serve the cached layer (osm_redis_cache).

```yaml
layers:
  - name: osm
    title: Omniscale OSM WMS - osm.omniscale.net
    sources: [osm_cache]
  - name: osm-redis-acche
    title: Omniscale OSM WMS - redis cache
    sources: [osm_redis_cache]
caches:
  osm_cache:
    grids: [webmercator]
    sources: [osm_wms]
  osm_redis_cache:
    sources: [osm_cache]
    grids: [webmercator]
    cache:
      type: redis
      default_ttl: 6000
      port: 6555
      host: 127.0.0.1
```

**Error stack trace:**

`Traceback (most recent call last):
  File "/mnt/hd1/POC/mapproxy_redis/mapproxy/test-venv/lib/python3.8/site-packages/mapproxy/wsgiapp.py", line 141, in __call__
    resp = self.handlers[handler_name].handle(req)
  File "/mnt/hd1/POC/mapproxy_redis/mapproxy/test-venv/lib/python3.8/site-packages/mapproxy/service/ows.py", line 38, in handle
    return self.services[service].handle(req)
  File "/mnt/hd1/POC/mapproxy_redis/mapproxy/test-venv/lib/python3.8/site-packages/mapproxy/service/base.py", line 30, in handle
    return handler(parsed_req)
  File "/mnt/hd1/POC/mapproxy_redis/mapproxy/test-venv/lib/python3.8/site-packages/mapproxy/service/wmts.py", line 102, in tile
    tile = tile_layer.render(request, coverage=limited_to, decorate_img=decorate_img)
  File "/mnt/hd1/POC/mapproxy_redis/mapproxy/test-venv/lib/python3.8/site-packages/mapproxy/service/tile.py", line 312, in render
    tile = self.tile_manager.load_tile_coord(tile_coord,
  File "/mnt/hd1/POC/mapproxy_redis/mapproxy/test-venv/lib/python3.8/site-packages/mapproxy/cache/tile.py", line 120, in load_tile_coord
    return self.load_tile_coords(
  File "/mnt/hd1/POC/mapproxy_redis/mapproxy/test-venv/lib/python3.8/site-packages/mapproxy/cache/tile.py", line 144, in load_tile_coords
    tiles = self._load_tile_coords(
  File "/mnt/hd1/POC/mapproxy_redis/mapproxy/test-venv/lib/python3.8/site-packages/mapproxy/cache/tile.py", line 167, in _load_tile_coords
    self.cache.load_tiles(tiles, with_metadata, dimensions=dimensions)
  File "/mnt/hd1/POC/mapproxy_redis/mapproxy/test-venv/lib/python3.8/site-packages/mapproxy/cache/base.py", line 51, in load_tiles
    if not self.load_tile(tile, with_metadata=with_metadata, dimensions=dimensions):
  File "/mnt/hd1/POC/mapproxy_redis/mapproxy/test-venv/lib/python3.8/site-packages/mapproxy/cache/redis.py", line 97, in load_tile
    tile_data = self.r.get(key)
  File "/mnt/hd1/POC/mapproxy_redis/mapproxy/test-venv/lib/python3.8/site-packages/redis/commands/core.py", line 1816, in get
    return self.execute_command("GET", name)
  File "/mnt/hd1/POC/mapproxy_redis/mapproxy/test-venv/lib/python3.8/site-packages/redis/client.py", line 1266, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/mnt/hd1/POC/mapproxy_redis/mapproxy/test-venv/lib/python3.8/site-packages/redis/connection.py", line 1461, in get_connection
    connection.connect()
  File "/mnt/hd1/POC/mapproxy_redis/mapproxy/test-venv/lib/python3.8/site-packages/redis/connection.py", line 713, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 10.45.130.11:6379. Connection refused.
[info] 10.45.130.11 - - [05/Jul/2023 11:48:46] "GET /service?layer=osm-cache-redis&style=&tilematrixset=webmercator&Service=WMTS&Request=GetTile&Version=1.0.0&Format=png&TileMatrix=4&TileCol=5&TileRow=9 HTTP/1.1" 500 -`

## Expected Behavior

When Redis server is not available or raises an error for some reason, MapProxy should fallback and serve the tiles from the configured source
## Actual Behavior

MapProxy doesn't serve the Redis cached layer (doesn't fallback to the source layer).
