### ISSUE TITLE
Incorrect bbox calculation of grid

### ISSUE THREAD

**Issue by drnextgis** [mapproxy/mapproxy#74]
If I try to transform `POINT(71 50)` from EPSG:4326 to EPSG:32644 in PostGIS or cs2cs utility I get the `POINT(-216025.317866142 5586720.84493467)`. But when I set up grid in mapproxy config:

```
services:
demo:
tms:

sources:
my_mapnik_source:
  type: mapnik
  use_mapnik2: True
  mapfile: /home/rykovd/mapnik-config.xml

grids:
utfgrid:
  srs: EPSG:32644
  tile_size: [256, 256]
  origin: ll
  res_factor: sqrt2
  bbox: [71,50,87,54]
  bbox_srs: EPSG:4326

caches:
ex1_cache:
  cache:
      type: file
      directory_layout: tms
  sources: [my_mapnik_source]
  grids: [utfgrid]

layers:
- name: merged_layer
  sources: [ex1_cache]
```

and try to query TileMap resource of TMS using `http://10.22.0.9:8080/tms/1.0.0/merged_layer/EPSG32644` URL I get response which contains the following bbox information:

```
<BoundingBox minx="-216025.317866" miny="5540547.36994" maxx="929865.502423" maxy="6029925.90671"/>
```

As you can see minx value is the same as in PostGIS, but miny is different - 5540547.36994 vs 5586720.84493467.
