### ISSUE TITLE
Image tile format jpeg doesn't work 

### ISSUE THREAD

**Issue by mar0321** [mapproxy/mapproxy#754]
Hi,
i'm seeding compact bundle cache (ArcGIS) and  i want to try jpeg instead of png
but no matter what tiles are stored in png anyway.

my code is in yaml is:

  image:
    format: image/jpeg
    image:
      encoding_options:
        jpeg_quality: 80

and it still provide png tiles.
Isn't there a bug? Or what am i doing wrong?

Thank's for response
Jan

**Comment by CaptainInler** [comment]
I also find this a bit strange as https://mapproxy.org/docs/latest/configuration.html#format states:
> The internal image format for the cache. Available options are `image/png`, `image/jpeg` etc.

I was not able to makte this working but only when disabling `format: image/jpeg`. But then the tiles will get stored as png.

For example with this yaml:
```` yaml
services:
  demo:
  tms:
    use_grid_names: true
    origin: 'nw'

layers:
  - name: swisstopo-swissimage
    title: swisstopo-swissimage
    sources: [swisstopo-swissimage_cache]

caches:
  swisstopo-swissimage_cache:
    grids: [webmercator]
    sources: [swissimage_src]
    #format: image/jpeg
    cache:
      type: file
      directory: C:/swissimage
      directory_layout: tms

sources:
  swissimage_src:
    type: tile
    grid: GLOBAL_WEBMERCATOR
    url: https://wmts.geo.admin.ch/1.0.0/ch.swisstopo.swissimage/default/current/3857/%(tms_path)s.jpeg
    coverage:
      bbox: [5.140242, 45.398181, 11.47757, 48.230651]
      srs: 'EPSG:4326'

grids:
  webmercator:
    base: GLOBAL_WEBMERCATOR
````

With `format: image/jpeg` enabled, there are no tiles stored in the cache-directory at all.
