### ISSUE TITLE
Clipping in coverage does not work when coverage is in cache

### ISSUE THREAD

**Issue by JacobJeppesen** [mapproxy/mapproxy#789]
## Context

`clip: true` in `coverage` is ignored for cache coverage.

## Expected Behavior

As I understand, `clip: true` in `coverage` should work the same in cache and source.

## Actual Behavior

If the coverage is defined in the cache instead of the source, clipping does not work. When you zoom in/out on a layer with the coverage in the cache, it can be seen how it loads the entire tile which touches the coverage bbox, instead of clipping it.

## Possible Fix

I have to admit that I don't know. Perhaps @shimoncohen (from https://github.com/mapproxy/mapproxy/pull/691) has an idea.

## Steps to Reproduce

Below is the configuration which I used to test. It also contains examples where multiple sources/caches are combined. My understanding is that the `opentopomap_coverage_in_source` and `opentopomap_coverage_in_cache` layers should look the same, and that the `opentopomap_combined_from_source` and `opentopomap_combined_from_cache` layers should look the same.
```
services:
  wmts:
    restful: true
    kvp: true
  demo:

layers:
  - name: opentopomap  # Works as intended
    title: OpenTopoMap
    sources: [ opentopomap_cache ]
  - name: opentopomap_coverage_in_source  # Works as intended
    title: OpenTopoMap Coverage in Source
    sources: [ opentopomap_cache_with_coverage1_in_source ]
  - name: opentopomap_coverage_in_cache  # Does not work as intended ('clip: true' is ignored)
    title: OpenTopoMap Coverage in Cache
    sources: [ opentopomap_cache_with_coverage1_in_cache ]
  - name: opentopomap_combined_from_source # Works as intended
    title: OpenTopoMap Combined from Source
    sources: [ opentopomap_cache_combined_from_source ]
  - name: opentopomap_combined_from_cache # Does not work as intended ('clip: true' and 'transparent: true' are ignored)
    title: OpenTopoMap Combined from Cache
    sources: [ opentopomap_cache_combined_from_cache ]

parts:
  coverages:
    intersection_coverage1: &intersection_coverage1
      clip: true
      intersection:
        - bbox: [ -110, 35, -105, 40 ]
          srs: 'EPSG:4326'
    intersection_coverage2: &intersection_coverage2
      clip: true
      intersection:
        - bbox: [ -100, 35, -95, 40 ]
          srs: 'EPSG:4326'

caches:
  opentopomap_cache:
    disable_storage: true
    grids: [ GLOBAL_WEBMERCATOR ]
    sources: [ opentopomap_source ]
  opentopomap_cache_with_coverage1_in_source:
    disable_storage: true
    grids: [ GLOBAL_WEBMERCATOR ]
    sources: [ opentopomap_source_coverage1 ]
  opentopomap_cache_with_coverage1_in_cache:
    grids: [ GLOBAL_WEBMERCATOR ]
    sources: [ opentopomap_source ]
    cache:
      type: file
      coverage: *intersection_coverage1
  opentopomap_cache_with_coverage2_in_cache:
    grids: [ GLOBAL_WEBMERCATOR ]
    sources: [ opentopomap_source ]
    cache:
      type: file
      coverage: *intersection_coverage2
  opentopomap_cache_combined_from_source:
    grids: [ GLOBAL_WEBMERCATOR ]
    sources: [ opentopomap_source_coverage1, opentopomap_source_coverage2 ]
  opentopomap_cache_combined_from_cache:
    grids: [ GLOBAL_WEBMERCATOR ]
    sources: [ opentopomap_cache_with_coverage1_in_cache, opentopomap_cache_with_coverage2_in_cache ]

sources:
  opentopomap_source:
    type: tile
    url: https://tile.opentopomap.org/%(z)s/%(x)s/%(y)s.png
    grid: GLOBAL_WEBMERCATOR
    transparent: true
  opentopomap_source_coverage1:
    type: tile
    url: https://tile.opentopomap.org/%(z)s/%(x)s/%(y)s.png
    grid: GLOBAL_WEBMERCATOR
    transparent: true
    coverage: *intersection_coverage1
  opentopomap_source_coverage2:
    type: tile
    url: https://tile.opentopomap.org/%(z)s/%(x)s/%(y)s.png
    grid: GLOBAL_WEBMERCATOR
    transparent: true
    coverage: *intersection_coverage2

globals:
  cache:
    meta_size: [1, 1]
    meta_buffer: 0
    base_dir: "/tmp/mapproxy-cache-coverage-test"
 
```

## Context

I would like to move the coverage from the source to the cache (@shimoncohen has some good explanations in https://github.com/mapproxy/mapproxy/pull/691 as to why this is sometimes preferred).

## Your Environment

* Version used: Installed from `master` branch on November 29 2023.
* Environment name and version (e.g. Python 2.7.5 with mod_wsgi 4.5.9): Python 3.10
* Server type and version:
* Operating System and version: Ubuntu 22.04
