### ISSUE TITLE
Tagged sources raise a warning on startup

### ISSUE THREAD

**Issue by weskamm** [mapproxy/mapproxy#989]
## Context
When using a tagged source like shown below, mapproxy raises a warning message on startup, which i think happens because of inconsistent type checking:

`2024-08-27 09:40:27,757 - WARNING - mapproxy.config - Supported layers for source 'testsource' are '0,1,2,3,5,6,7' but tagged source requested layers '0'`

## Expected Behavior
No warnings on startup

## Actual Behavior
Warnings on startup

## Possible Fix
Check if this line https://github.com/mapproxy/mapproxy/blob/df813a8366c66cbaed3ba91f083fd460d867ab4d/mapproxy/config/validator.py#L176
correctly handles all allowed datatypes. I think the `issubset` call fails under some circumstances.

## Steps to Reproduce
configure a layer like
```
layers:
  - name: test
    title: test
    sources: ['testsource:0']

sources:
  testsource:
    type: wms
    req:
      url: https://example.com
      layers: 0,1,2,3,5,6,7
```
Startup MapProxy, you should see the warning
